### ISSUE TITLE
I tried to install Linuxbrew this weekend but..

### ISSUE THREAD

**Issue by Tjarko-Holtjer** [athrunsun/homebrew-linuxbinary#13]
Error: Invalid formula: /home/Tjarko/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ios-deploy.rb
unknown version nil
Error: Invalid formula: /home/Tjarko/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/sbjson.rb
unknown version nil
Error: Invalid formula: /home/Tjarko/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/zzz.rb
unknown version nil
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/Tjarko/.linuxbrew/bin/brew tap homebrew/core -q

I am unable to remove this error in the Tap manually... Every action I would want to do with brew results in the above errors...

to remove the errors I dit this in the directory where they were missing:
[Tjarko@localhost Homebrew]$ cp tap.rb ios-deploy.rb
[Tjarko@localhost Homebrew]$ cp tap.rb sbjson.rb
[Tjarko@localhost Homebrew]$ cp tap.rb zzz.rb

Note that if you use the commands ios-deploy, sbjson and/or zzz they now act like tap...

**Comment by athrunsun** [comment]
Hi @Tjarko-Holtjer, what is the issue you're having with homebrew-linuxbinary? If no, I suggest you submit your issue in [homebrew-core](https://github.com/Linuxbrew/homebrew-core) to gain more attention from core linuxbrew contributors.
