### ISSUE TITLE
Best way to implement appimage support in linuxbrew

### ISSUE THREAD

**Issue by emanresusername** [athrunsun/homebrew-linuxbinary#15]
hoping to get some advice/ideas from similar projects on [this issue](https://github.com/Linuxbrew/homebrew-core/issues/4357)

(please excuse the copypasta 😅 thought this'd be the best combo of efficiency, related-github-repo-synnergy and visibility/discoverability for the relevant communities/contributers/etc)

**Comment by athrunsun** [comment]
I think we can just treat appimage apps as executables, just like you discussed in the linked issue.

I also took at the app list [here](https://appimage.github.io/apps/), AppImage team do provide their updater named [AppImageUpdate](https://appimage.github.io/AppImageUpdate/), however in the list very few apps are able to use that updater.

I'll start with a new repo to place all appimage apps I feel popular (neovim, LightTable, XnViewMP, etc.).

Feel free to tell me what you think.

**Comment by emanresusername** [comment]
sounds great to me! lmk the repo and i'll contribute where i can!
![](http://i0.kym-cdn.com/photos/images/facebook/001/240/075/90f.png)

**Comment by athrunsun** [comment]
New tap is created: https://github.com/athrunsun/homebrew-appimage

Closing this issue.
