### ISSUE TITLE
''Prefer 64'' errors in homebrew/linuxbrew 1.8.6

### ISSUE THREAD

**Issue by JuPlutonic** [athrunsun/homebrew-linuxbinary#27]
When I tried to upate Linuxbrew(```brew update && brew update```)
I got 50 errors:
[Error-- Failed to import.txt](https://github.com/athrunsun/homebrew-linuxbinary/files/2745339/Error--.Failed.to.import.txt)

This merge shows how it was solved in homebrew/brew:
https://github.com/Homebrew/brew/pull/5477

**Comment by athrunsun** [comment]
OK, so `MacOS.prefer_64_bit?` is deprecated. I'll remove it from all formulaes.

**Comment by athrunsun** [comment]
Fixed in [this commit](https://github.com/athrunsun/homebrew-linuxbinary/commit/ff501eeaf7f650816efd68450211b8b23e5d2fa6).

@JuPlutonic Please verify on your end and reopen this issue if necessary.

**Comment by JuPlutonic** [comment]
Fixed
