### ISSUE TITLE
delete skype formula because it 32-bit only.

### ISSUE THREAD

**Issue by JuPlutonic** [athrunsun/homebrew-linuxbinary#39]
Don't introduce to people outdated Skype

[ ]. Because it can't run not only on x86_64-only OSes, but on some mutliarch systems.

[]. Quality of network service on outdated Skype is worst than on web.sype.com // Electron versions of web-skype // skypeforlinux Deb and RPM packages.

**Comment by athrunsun** [comment]
@JuPlutonic Skype is removed, thanks for your suggestion!
