### ISSUE TITLE
Please update the Julia formula.

### ISSUE THREAD

**Issue by ivaquero** [athrunsun/homebrew-linuxbinary#43]
Hi, I just found this amazing project. However, the Julia formula is a very old version. Please update it. 

BTW, I see the script is not hard to understand, I wonder if I can help with this since I also maintain a cask on MacOS.

Thank you.

**Comment by athrunsun** [comment]
@integzz Hi, thanks for your attention.

You said you maintain a cask so I assume you know the steps of updating a formula. So go ahead forking this repo and updating `url`, `version` and `sha256` field in `Formula/julia-binary.rb`, and submit your PR, I'll merge it.

> I wonder if I can help with this

Do you mean adding you as a collaborator of this repo?

**Comment by ivaquero** [comment]
It's nice to receive your reply. I will try my best to submit the PR.

However, the cask I maintain is for mac dmg, which is pretty easy to deal with. I am not sure whether I am capable of handling the binaries in this cask. So, though I wish that I could join you, before being allowed, just see if I can complete some PRs first.

Again, thanks for your great idea of this cask.

**Comment by athrunsun** [comment]
Actually homebrew and homebrew-cask have many things in common.

I'll look into your PR right away.

**Comment by athrunsun** [comment]
Close on behalf of #44
