### ISSUE TITLE
Teamviewer: SHA256 mismatch

### ISSUE THREAD

**Issue by agustif** [athrunsun/homebrew-linuxbinary#9]
Error: SHA256 mismatch
Expected: b397b67419270d74470d2a59c48e48f5436ddf241b100170bc1ed556f3f65fd3
Actual: ac5955352fed3d68b65c9aef9e6d40bac8440bd8a7627e15233b41c0babf24db
Archive: /home/agus/.cache/Homebrew/teamviewer-11.0.57095.tar.xz
To retry an incomplete download, remove the file above.

**Comment by athrunsun** [comment]
This issue is resolved, please get latest master. Thanks.

**Comment by agustif** [comment]
Yup, sorry man, brew update fixed it. Will try that before opening issues

**Comment by athrunsun** [comment]
@agustif No you misunderstood. I fixed the issue because you reported it. I pushed that fix directly to master so getting latest on your side will do it.

Thanks for reporting this issue, don't hesitate to report issues in the future! :-)

**Comment by agustif** [comment]
Oh nice, yeah I totally misunderstood your feedback, sorry for that, glad I could help.
